import type { Habit } from './types';

export const initialHabits: Habit[] = [
  {
    id: '1',
    title: 'Read for 15 minutes',
    description: 'Dive into a book to expand knowledge.',
    completed: false,
    streak: 12,
    longestStreak: 25,
    goal: 30,
    completions: [],
  },
  {
    id: '2',
    title: 'Morning Meditation',
    description: '10 minutes of guided meditation.',
    completed: true,
    streak: 5,
    longestStreak: 5,
    goal: 30,
    completions: [],
  },
  {
    id: '3',
    title: 'Go for a 30-minute walk',
    description: 'Get some fresh air and exercise.',
    completed: false,
    streak: 2,
    longestStreak: 10,
    goal: 30,
    completions: [],
  },
  {
    id: '4',
    title: 'Drink 8 glasses of water',
    description: 'Stay hydrated throughout the day.',
    completed: true,
    streak: 43,
    longestStreak: 43,
    goal: 30,
    completions: [],
  },
  {
    id: '5',
    title: 'Write in a journal',
    description: 'Reflect on the day and clear your mind.',
    completed: false,
    streak: 0,
    longestStreak: 7,
    goal: 30,
    completions: [],
  },
];